### ISSUE TITLE
Using Previews

### ISSUE THREAD

**Issue by damartin1** [daneden/Twift#41]
Good morning,

Am I missing something here? I am trying to feed a User array into my preview, but for the life of me I cannot get this thing to work. Below is a snippet, the error is "Type Twift has no member User", however this a nearly exact copy of the results received from the api call. Thoughts.

struct FollowingView_Previews: PreviewProvider {
    static var previews: some View {
        let users: [User] = [Twift.User(id: "1445771133337235470", name: "Oppenheimer", username: "OppenheimerFilm", createdAt: Date(), protected: false, withheld: WithheldInformation, location: "nowhere", pinnedTweetId: "", url: "", description: "", verified: "", entities: "", profileImageUrl: "", publicMetrics: "")]
        FollowingView(users: users)
    }
}

**Comment by damartin1** [comment]
anyone? someone? help :)

**Comment by roblack** [comment]
Is the `let users: [User]` using your own user or Twift user? If it is your own, maybe use a different name?
Also, I might be off the mark here, but `Twift.User` can be used in declaring the type, not when initializing it? Basically replace these two, see if it helps: `let users: [Twift.User] = [User(id:...`

**Comment by damartin1** [comment]
Thanks for the reply. I tried that but get a "User' is not a member type of class 'Twift.Twift'". I also did the import struct Twift.User, but get the same error.

**Comment by roblack** [comment]
If you delete `Twift.` a true error will reveals itself :) 
User inside Twift has no initialiser, so you cannot really mock data like so.

Not sure if you can try to extend it and try if that works, or, the way I did it...store it in UserDefaults when fetching real data and use that for some offline tests :)

**Comment by damartin1** [comment]
When I take off Twift I get the "Missing argument for parameter 'from' in call insert 'from: <#Decoder#>, '". Can you expand upon using UserDefaults? I am wanting to be able to see the preview live for UI modifications and just pass it some random data to create it.

**Comment by roblack** [comment]
Since you need to use mock data to have it in the preview, and as it is easier to actually have real data there, you can log in once, save user data, and then in the preview fetch that data through userDefaults.

I made this to encode/decode stuff for userData. Just replace MODEL and KEY with proper stuff you are trying to encode/decode :) Hope this helps!

```swift
extension UserDefaults {
    static func encodeUser(item: MODEL) {
        Task {
            let encoder = JSONEncoder()
            if let data = try? encoder.encode(item) {
                UserDefaults.standard.set(data, forKey: KEY)
            }
        }
        
    }
  
  static func decodeITEM() -> MODEL? {
    let decoder = JSONDecoder()
    if let data = UserDefaults.standard.data(forKey: KEY),
       var decodedMODEL = try? decoder.decode(MODEL.self, from: data) {
      return decodedMODEL
    }
      return nil
  }
  
}
```

**Comment by damartin1** [comment]
Thanks will give this a whirl!

**Comment by daneden** [comment]
As @roblack pointed out, Twift’s models don’t have initialisers besides decoding from JSON payloads. I originally designed it this way thinking that you'd only need to instantiate models for Tweets and related objects (such as Polls), and created specific models for those instantiations (`MutableTweet`), but SwiftUI previews are a good example of where it would be useful to instantiate your own models for other types. I can revisit this design decision!

**Comment by damartin1** [comment]
> 

So if I have an array of User Data from .getFollowing that I am returning, how does this fit into the Model/Key piece?

**Comment by roblack** [comment]
If you have that data, save it in UserDefaults when fetched. Then, in the preview, or on the next app launch, just use that data instead.
That is my assumption tho...not 100% confident you can get defaults data in the preview. I would hope so? 🤷‍♂️

**Comment by damartin1** [comment]
Thank! I'll give this a shot! Appreciate the guidance!

**Comment by daneden** [comment]
Yeah I wouldn't use UserDefaults for this; a JSON file that you decode is probably the right approach (which is what I do for other apps, for example [Zeitgeist](https://github.com/daneden/Zeitgeist/blob/v3/Shared/Helpers/PlaceholderData.swift)). But if it feels more natural to use the model(s) directly I'm open to changing Twift to enable this if there's enough demand!

**Comment by damartin1** [comment]
Thanks everyone, got it working!
