### ISSUE TITLE
Submitting to appstore requires the ability to report post

### ISSUE THREAD

**Issue by arbyruns** [daneden/Twift#48]
I was rejected from the app store since I did not have a way for content to be reported. Just a heads up for other users that maybe using Twift.

Guideline 1.2 - Safety - User Generated Content

We found in our review that your app includes user-generated content but does not have all the required precautions. Apps with user-generated content must take specific steps to moderate content and prevent abusive behavior.

Next Steps

To resolve this issue, please revise your app to implement the following precautions:

- Require that users agree to terms (EULA) and these terms must make it clear that there is no tolerance for objectionable content or abusive users

- A mechanism for users to flag objectionable content

Resources

Learn more about our policies for user-generated content in [App Store Review Guideline 1.2](https://developer.apple.com/app-store/review/guidelines/#user-generated-content).

**Comment by roblack** [comment]
oh wow 😬
Had no idea about this, thank you for letting us know.
Daym...I would expect as we are making a Twitter api app that there is no need for us to implement such a thing....hm...Gotta make sure the popup is there I guess 😅

**Comment by arbyruns** [comment]
I don't see that v2 has a way to report spam (there is in v1 thought) but can block or mute users. Can you expand on this _Gotta make sure the popup is there I guess_? I'm trying to figure out how I can meet this requirement.

**Comment by roblack** [comment]
Well, I guess on first launch you have to have  screen saying "to use this app you must agree to EULA terms bla bla...and have a link to the terms as well.

You can even frame it as "by closing this alert you agree" 😅

As for flagging....mute is quite ok i guess and should be good enough. They just frame it as "flagging" as that is usually an option that you have

**Comment by arbyruns** [comment]
Closing the loop on this, but blocking the user and then redirecting to the user profile that was blocked satisfied Apple Review policy.
