### ISSUE TITLE
Is it possible to have multiple devices

### ISSUE THREAD

**Issue by arbyruns** [daneden/Twift#49]
I'm finding that using Twift only allows for one devices logged in at a time. Is this a limitation of Twitter or Twift?

**Comment by roblack** [comment]
Oh this is a good question. I explored some ways to sync logins via icloud to remedy against it, as it it quite obvious when using on sim and then the phone.

I guess if you build the app for iPhone only, not many users would be affected, but still, worth exploring if it is possible to remedy somehow.

**Comment by arbyruns** [comment]
I have this issue with physical devices. Did syncing iCloud work for you?

**Comment by roblack** [comment]
It did, but on the first launch it takes some time to sync. I tried using Zephyr https://github.com/ArtSabintsev/Zephyr which worked nicely.
But still switching back and forth can cause some issues 🤷‍♂️

**Comment by arbyruns** [comment]
I'll give that a shot because using 
`kSecAttrSynchronizable` hasn't been working for me.

**Comment by arbyruns** [comment]
@roblack closing the loop on this. Using Zephyr seemed to do the trick. Thanks!
